### ISSUE TITLE
CORS issue with Http POST/GET accessing external API.

### ISSUE THREAD

**Issue by polcham** [ionic-team/cordova-plugin-wkwebview-engine#158]
Hi,

Description:
When I do Http POST/GET requests to an external API, I always get an {isTrusted: true} response.
It may have something to do with a CORS issue with this plugin.

Replicate: 
add the plugin cordova-plugin-wkwebview-engine and deploy on real iOS device then do a http.post/get request.

**Comment by touficzayed** [comment]
Same problem here. This plugin improves performance a lot, but it's impossible to make request to external API, even though CORS is set up on the server (allow origin "*").

I mitigate the problem by using cordova http to make request, but this plugin is not perfect and it has it's own bugs too.
It would be much much more simple if ajax request could work with this plugin.

**Comment by manucorporat** [comment]
@touficzayed @polcham well, it is not impossible, we are successfully using WK with a lot of external services.

You need to implement CORS correctly, in your server. ` allow origin "*"` is not CORS. You need to implement preflight requests, specify the custom headers you use etc.

I think you should try to revisit how you are implementing CORS in your services and try again.

**Comment by janpio** [comment]
If you need more help, try posting at https://forum.ionicframework.com/. We are quite used to telling people how to implement all things needed for CORS...

**Comment by touficzayed** [comment]
Hi @manucorporat and @janpio  and thank you for your replies.

CORS in my server is correctly implemented, including Access-Control-Allow-Origin (in my first message I didn't take the time to write the header in it's full length, it was just a hint). I'm using Amazon API-Gateway along with serverless framework to deploy my web services, so the headers are generated automatically and properly.

I my android version or in chrome I can check that the prefligth requests are sent, and that all my headers are OK. And it works in android and chrome (in local debug mode).

Furthermore, the wkwebview-engine plugin once worked for my app some months ago (around march/april), but it's not the case anymore.

I believe you when you say that it works for you and you use it in multiple projects, but I suspect in my case that there must be incompatibility with other plugins.

Since I need this plugin because it improves the performance and stability of my app a lot, I use the cordova http plugin to bypass Ajax request, and it's ok, but as I said before this plugin has also its own limitations.
